# Pitchfork is a minimal process manager that we use for managing test dependencies.
# It's installed and used by mise.toml tasks.

[daemons.sanvil]
run = "mise run sanvil::start --port 8545"
ready_port = 8545

[daemons.sreth-local]
run = "mise run sreth::start-local --port 8545"
ready_port = 8545
