# Pitchfork is a minimal process manager that we use for managing test dependencies.
# It's installed and used by mise.toml tasks.

[daemons.sanvil]
run = "sanvil --port 8545"
ready_port = 8545

[daemons.sreth-local]
run = "cargo run --bin seismic-reth -- node --dev --dev.block-time 2s --http --http.port 8545 --ws --ws.port 8545 --enclave.mock-server"
dir = "../seismic-reth"
ready_port = 8545
